micronaut:
  application:
    name: mydb
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/mydb`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    package-to-scan:
      - 'com.app.mydb'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        